name: Java CI/CD

on:
  push:
    branches: [ "main", "dev" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: [ ubuntu-latest ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Make application.yml
        run: |
          cd ./src/main/resources
          rm -f application.yml application-*.yml
          touch ./application.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml

      - name: Make executable gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t app .
          docker tag app ${{ secrets.DOCKER_USERNAME }}/delivery:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/delivery:latest

      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: |
            cd /home/ubuntu
            docker-compose pull
            docker-compose down
            docker-compose up -d
            docker image prune -f